**CREATRING A BAG OF WORD MODEL USING SCIKITLEARN**

IMPORTING RELEVANT LIBRARIES

In [22]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer


READING THE TEXT DOCUMENT FROM THE FILE PATH

In [3]:
text = ['This is a line',
       'This is another line',
       'Completely different line']

**BUILD THE COUNT VECTORIZER**

In [10]:
# create an instance of the count vectorizer
cv = CountVectorizer()
cv1 = CountVectorizer(stop_words='english')

In [11]:
cv

CountVectorizer()

In [12]:
cv1

CountVectorizer(stop_words='english')

In [7]:
# fit the model on the text data
sparse_matrix = cv.fit_transform(text)

In [8]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [9]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [13]:
# fit the model on the text data
sparse_matrix1 = cv1.fit_transform(text)

In [14]:
sparse_matrix1.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [15]:
cv1.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

CREATE A TF-IDF FROM THE VECTORIZER

In [18]:
# create an instance of the tfidf transformer
tfidf = TfidfTransformer()

In [19]:
# fit the model on the bag of words sparse matrix
tfidf_matrix = tfidf.fit_transform(sparse_matrix)

In [20]:
tfidf_matrix

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [21]:
tfidf_matrix.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

CREATE AN INSTANCE OF TF-IDF VECTORIZER

In [23]:
tfidf_vectorizer = TfidfVectorizer()

In [24]:
result = tfidf_vectorizer.fit_transform(text)

In [25]:
result

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>